packages:
    - 'packages/*'
    - 'packages/app/*'

allowBuilds:
    '@parcel/watcher': true
    '@prisma/engines': true
    esbuild: true
    prisma: true

minimumReleaseAgeExclude:
    - fast-uri@3.1.4
    - postcss@8.5.18
    - brace-expansion@5.0.8
